SELECT * FROM PRODUCT
--------------------------
SELECT * FROM SALES
--------------------------
SELECT * FROM CUSTOMER
--------------------------
SELECT * FROM PRODUCT WHERE ID_PRODUCT = '001'
--------------------------
SELECT NAME FROM PRODUCT WHERE ID_PRODUCT = '008'
--------------------------
/*JOIN TWO TABLES*/
--------------------------
SELECT * FROM PRODUCT P, SALES S
--RESULT WILL BE 80 LINES BECAUSE PRODUCT HAS 10 LINES AND SALES HAS 8 LINES SO 8*10 = 80 LINES
--------------------------
SELECT * FROM PRODUCT P, SALES S WHERE S.ID_PRODUCT = P.ID_PRODUCT
--------------------------
SELECT * FROM PRODUCT P, SALES S WHERE S.ID_PRODUCT = P.ID_PRODUCT AND S.ID_CUSTOMER = 2
--------------------------
SELECT * FROM PRODUCT P, SALES S, CUSTOMER C 
WHERE S.ID_PRODUCT = P.ID_PRODUCT AND S.ID_CUSTOMER = C.ID_CUSTOMER AND S.AMOUNT > 10.0
